function getJSON(){
var JSON = "["
+"    {"
+"      \"sha\": \"84de17b89748fc995cbcfb4dd779400d29b648db\","
+"      \"node_id\": \"MDY6Q29tbWl0MTUzNjM4NzcxOjg0ZGUxN2I4OTc0OGZjOTk1Y2JjZmI0ZGQ3Nzk0MDBkMjliNjQ4ZGI=\","
+"      \"commit\": {"
+"        \"author\": {"
+"          \"name\": \"BenoitCochet\","
+"          \"email\": \"default-user@gmail.com\","
+"          \"date\": \"2018-10-19T06:01:38Z\""
+"        },"
+"        \"committer\": {"
+"          \"name\": \"default user\","
+"          \"email\": \"default-user@gmail.com\","
+"          \"date\": \"2018-10-19T06:01:38Z\""
+"        },"
+"        \"message\": \"implementation of search function\","
+"        \"tree\": {"
+"          \"sha\": \"aeb2df1bf3d7b94de58db73135c36c3fb6de6383\","
+"          \"url\": \"https://api.github.com/repos/TeofiloJ/github-ynov-vue/git/trees/aeb2df1bf3d7b94de58db73135c36c3fb6de6383\""
+"        },"
+"        \"url\": \"https://api.github.com/repos/TeofiloJ/github-ynov-vue/git/commits/84de17b89748fc995cbcfb4dd779400d29b648db\","
+"        \"comment_count\": 0,"
+"        \"verification\": {"
+"          \"verified\": false,"
+"          \"reason\": \"unsigned\","
+"          \"signature\": null,"
+"          \"payload\": null"
+"        }"
+"      },"
+"      \"url\": \"https://api.github.com/repos/TeofiloJ/github-ynov-vue/commits/84de17b89748fc995cbcfb4dd779400d29b648db\","
+"      \"html_url\": \"https://github.com/TeofiloJ/github-ynov-vue/commit/84de17b89748fc995cbcfb4dd779400d29b648db\","
+"      \"comments_url\": \"https://api.github.com/repos/TeofiloJ/github-ynov-vue/commits/84de17b89748fc995cbcfb4dd779400d29b648db/comments\","
+"      \"author\": {"
+"        \"login\": \"DefaultUser\","
+"        \"id\": 34065590,"
+"        \"node_id\": \"MDQ6VXNlcjM0MDY1NTkw\","
+"        \"avatar_url\": \"https://avatars3.githubusercontent.com/u/34065590?v=4\","
+"        \"gravatar_id\": \"\","
+"        \"url\": \"https://api.github.com/users/TeofiloJ\","
+"        \"html_url\": \"https://github.com/TeofiloJ\","
+"        \"followers_url\": \"https://api.github.com/users/TeofiloJ/followers\","
+"        \"following_url\": \"https://api.github.com/users/TeofiloJ/following{/other_user}\","
+"        \"gists_url\": \"https://api.github.com/users/TeofiloJ/gists{/gist_id}\","
+"        \"starred_url\": \"https://api.github.com/users/TeofiloJ/starred{/owner}{/repo}\","
+"        \"subscriptions_url\": \"https://api.github.com/users/TeofiloJ/subscriptions\","
+"        \"organizations_url\": \"https://api.github.com/users/TeofiloJ/orgs\","
+"        \"repos_url\": \"https://api.github.com/users/TeofiloJ/repos\","
+"        \"events_url\": \"https://api.github.com/users/TeofiloJ/events{/privacy}\","
+"        \"received_events_url\": \"https://api.github.com/users/TeofiloJ/received_events\","
+"        \"type\": \"User\","
+"        \"site_admin\": false"
+"      },"
+"      \"committer\": {"
+"        \"login\": \"defaultUser\","
+"        \"id\": 34065590,"
+"        \"node_id\": \"MDQ6VXNlcjM0MDY1NTkw\","
+"        \"avatar_url\": \"https://avatars3.githubusercontent.com/u/34065590?v=4\","
+"        \"gravatar_id\": \"\","
+"        \"url\": \"https://api.github.com/users/TeofiloJ\","
+"        \"html_url\": \"https://github.com/TeofiloJ\","
+"        \"followers_url\": \"https://api.github.com/users/TeofiloJ/followers\","
+"        \"following_url\": \"https://api.github.com/users/TeofiloJ/following{/other_user}\","
+"        \"gists_url\": \"https://api.github.com/users/TeofiloJ/gists{/gist_id}\","
+"        \"starred_url\": \"https://api.github.com/users/TeofiloJ/starred{/owner}{/repo}\","
+"        \"subscriptions_url\": \"https://api.github.com/users/TeofiloJ/subscriptions\","
+"        \"organizations_url\": \"https://api.github.com/users/TeofiloJ/orgs\","
+"        \"repos_url\": \"https://api.github.com/users/TeofiloJ/repos\","
+"        \"events_url\": \"https://api.github.com/users/TeofiloJ/events{/privacy}\","
+"        \"received_events_url\": \"https://api.github.com/users/TeofiloJ/received_events\","
+"        \"type\": \"User\","
+"        \"site_admin\": false"
+"      },"
+"      \"parents\": ["
+"        {"
+"          \"sha\": \"2a246cf92431ad7736242113e7af460839b27111\","
+"          \"url\": \"https://api.github.com/repos/TeofiloJ/github-ynov-vue/commits/2a246cf92431ad7736242113e7af460839b27111\","
+"          \"html_url\": \"https://github.com/TeofiloJ/github-ynov-vue/commit/2a246cf92431ad7736242113e7af460839b27111\""
+"        }"
+"      ]"
+"    }"
+"  ]";

return JSON

}

function getNom(){
  var str = "["
+"    {"
+"        \"username\": \"Mokui\","
+"        \"prenom\": \"Yanis\","
+"        \"nom\": \"Dando\""
+"    },"
+"    {"
+"        \"username\": \"Killy85\","
+"        \"prenom\": \"Nicolas\","
+"        \"nom\": \"Goureau\""
+"    },"
+"    {"
+"        \"username\": \"Nair0fl\","
+"        \"prenom\": \"?\","
+"        \"nom\": \"?\""
+"    },"
+"    {"
+"        \"username\": \"raphaelCharre\","
+"        \"prenom\": \"Raphael\","
+"        \"nom\": \"Charre\""
+"    },"
+"    {"
+"        \"username\": \"mathiasLoiret\","
+"        \"prenom\": \"Mathias\","
+"        \"nom\": \"Loiret\""
+"    },"
+"    {"
+"        \"username\": \"thomaspich\","
+"        \"prenom\": \"Thomas\","
+"        \"nom\": \"Pichard\""
+"    },"
+"    {"
+"        \"username\": \"TeofiloJ\","
+"        \"prenom\": \"Teofilo\","
+"        \"nom\": \"Jeannot\""
+"    },"
+"    {"
+"        \"username\": \"Grigusky\","
+"        \"prenom\": \"Gregoire\","
+"        \"nom\": \"Meunier\""
+"    },"
+"    {"
+"        \"username\": \"Dakistos\","
+"        \"prenom\": \"Mathias\","
+"        \"nom\": \"Dupont\""
+"    },"
+"    {"
+"        \"username\": \"mael61\","
+"        \"prenom\": \"Mael\","
+"        \"nom\": \"Maillard\""
+"    },"
+"    {"
+"        \"username\": \"KevinPautonnier\","
+"        \"prenom\": \"Kevin\","
+"        \"nom\": \"Pautonnier\""
+"    },"
+"    {"
+"        \"username\": \"BenoitCochet\","
+"        \"prenom\": \"Benoit\","
+"        \"nom\": \"Cochet\""
+"    },"
+"    {"
+"        \"username\": \"sfongue\","
+"        \"prenom\": \"?\","
+"        \"nom\": \"?\""
+"    },"
+"    {"
+"        \"username\": \"ClementCaillaud\","
+"        \"prenom\": \"Clement\","
+"        \"nom\": \"Caillaud\""
+"    },"
+"    {"
+"        \"username\": \"gfourny\","
+"        \"prenom\": \"Guillaume\","
+"        \"nom\": \"Fourny\""
+"    },"
+"    {"
+"        \"username\": \"LordInateur\","
+"        \"prenom\": \"Matthieu\","
+"        \"nom\": \"Fournier\""
+"    },"
+"    {"
+"        \"username\": \"AntoineGOSSET\","
+"        \"prenom\": \"Antoine\","
+"        \"nom\": \"Fournier\""
+"    },"
+"    {"
+"        \"username\": \"etienneYnov\","
+"        \"prenom\": \"Etienne\","
+"        \"nom\": \"Hounguevou\""
+"    },"
+"    {"
+"        \"username\": \"Coblestone\","
+"        \"prenom\": \"Antoine\","
+"        \"nom\": \"Drouard\""
+"    },"
+"    {"
+"        \"username\": \"AlexDesvallees\","
+"        \"prenom\": \"Alex\","
+"        \"nom\": \"Desvallees\""
+"    },"
+"    {"
+"        \"username\": \"rudy8530\","
+"        \"prenom\": \"Rudy\","
+"        \"nom\": \"Schoepfer\""
+"    },"
+"    {"
+"        \"username\": \"benjaminbra\","
+"        \"prenom\": \"Benjamin\","
+"        \"nom\": \"Brasseur\""
+"    },"
+"    {"
+"        \"username\": \"alixnzt\","
+"        \"prenom\": \"Alix\","
+"        \"nom\": \"Nouzillat\""
+"    }"
+"]";
  return str;
}

function getProjet(){
	var str = "["
+"    {"
+"        \"nomProjet\": \"github-ynov-vue\""
+"    }]";
	
	return str;
}